config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators

  root to: "home#home"

  namespace :admin do
    root to: "home#home"
    resources "events"
  end

  namespace :profile do
    root to: "profiles#profile"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
require 'icalendar'

class Availability < ApplicationRecord
  validates_presence_of :date

  def create_availabilities(bookings)
    availabilities = bookings.each.map do |booking|
      {
        start_time: booking.dtstart,
        finish_time: booking.dtend,
      }
    end
    Availability.insert_all(availabilities)
  end

  private

  Booking = Struct.new(:date, :duration)

  def self.read_bookings_file
    cal_file = File.open("basic.ics")
    calendars = Icalendar::Calendar.parse(cal_file)
    calendars.first.events.take(5).map do |event|
      puts "start date-time: #{event.dtstart}"
      puts "finsih finish-time: #{event.dtend}"
      puts "description: #{event.description}"
      puts "start date-time timezone: #{event.dtstart.ical_params['tzid']}"
      puts "summary: #{event.summary}"
      puts "########"
    end+
    create_availabilities(bookings)
  end

  def self.make_bookings_file
    # Create a calendar with an event (standard method)
    cal = Icalendar::Calendar.new
    cal.event do |e|
      e.dtstart     = Icalendar::Values::Date.new('20050428')
      e.dtend       = Icalendar::Values::Date.new('20050429')
      e.summary     = "Meeting with the man."
      e.description = "Have a long lunch meeting and decide nothing..."
      e.ip_class    = "PRIVATE"
    end

    cal.publish
    File.write('test.ics', cal.to_ical)

  end
end

app/models/event.rb
require 'icalendar'

class Event < ApplicationRecord
  validates_presence_of :date
  belongs_to :event_type

  def create_availabilities(bookings)
    availabilities = bookings.each.map do |booking|
      {
        start_time: booking.dtstart,
        finish_time: booking.dtend,
      }
    end
    Event.insert_all(availabilities)
  end

  private

  Booking = Struct.new(:date, :duration)

  def self.read_bookings_file
    cal_file = File.open("basic.ics")
    calendars = Icalendar::Calendar.parse(cal_file)
    calendars.first.events.take(5).map do |event|
      puts "start date-time: #{event.dtstart}"
      puts "finsih finish-time: #{event.dtend}"
      puts "description: #{event.description}"
      puts "start date-time timezone: #{event.dtstart.ical_params['tzid']}"
      puts "summary: #{event.summary}"
      puts "########"
    end+
    create_availabilities(bookings)
  end

  def self.make_bookings_file
    # Create a calendar with an event (standard method)
    cal = Icalendar::Calendar.new
    cal.event do |e|
      e.dtstart     = Icalendar::Values::Date.new('20050428')
      e.dtend       = Icalendar::Values::Date.new('20050429')
      e.summary     = "Meeting with the man."
      e.description = "Have a long lunch meeting and decide nothing..."
      e.ip_class    = "PRIVATE"
    end

    cal.publish
    File.write('test.ics', cal.to_ical)

  end
end

app/models/event_type.rb
class EventType < ApplicationRecord
  has_many :events
end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    before_action :authenticate_administrator!
    layout "admin"

    private
  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < AdminController
    before_action :set_event
    include ApplicationHelper

    def index
      @events = Event.all
    end

    def new
      @event = Event.new
    end

    def create
      event = Event.new(event_params)
      if event.save
        flash[:success] = "#{formatted_date(event.date)} event has been created"
      else
        flash[:warning] = "An error has occurred please try again"
      end
      redirect_to admin_events_path
    end

    def edit
    end

    def update
      if @event.update(event_params)
        flash[:success] = "#{formatted_date(@event.date)} event has been updated"
      else
        flash[:warning] = "An error has occurred please try again"
      end
      redirect_to admin_events_path
    end

    def destroy
      @event.destroy
      redirect_to admin_events_path
    end

    private

    def event_params
      params.fetch(:event).permit(:date, :start_time, :finish_time)
    end

    def set_event
      @event = Event.find_by(params[:id])
    end
  end
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < AdminController
    def home
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_date(date)
    date.present? ? date.strftime("%Y-%m-%d") : ""
  end

  def formatted_time(time)
    time.present? ? time.strftime("%H:%M:%S") : ""
  end
end

app/views/admin/events/_form.html.erb
<%= form_for [:admin, event] do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event model from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.date_field :date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.time_field :start_time, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.time_field :finish_time, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/events/edit.html.erb
<%= render partial: "form", locals: { event: @event } %>

app/views/admin/events/index.html.erb
<%= link_to "New", new_admin_event_path %>

<table class="admin-table">
  <tr>
    <th>Date</th>
    <th>Start Time</th>
    <th>Finish Time</th>
    <th>Actions</th>
  </tr>
  <% @events.each do |event| %>
    <tr>
      <td><%= formatted_date(event.date) %></td>
      <td><%= formatted_time(event.start_time) %></td>
      <td><%= formatted_time(event.finish_time) %></td>
      <td>
        <%= link_to "Edit", edit_admin_event_path(event) %>
        <%= link_to "Delete", admin_event_path(event), data: {confirm: "Are you sure you want to delete this?"}, method: :delete, class: "btn btn-small btn-danger" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/events/new.html.erb
<%= render partial: "form", locals: { event: @event } %>

app/views/admin/home/home.html.erb
<h1>Admin home page</h1>


<p><%= current_administrator.email %></p>

<%= link_to "sign out", destroy_administrator_session_path, method: :delete %>

app/views/home/home.html.erb
<%= javascript_pack_tag "calendar" %>

<div class="calendar-pageContainer">
  <div class="calendar-mainContainer">
    <%= link_to "Admin sign in", new_administrator_session_path %>

    <% if current_administrator %>
      <p><%= current_administrator.email %></p>
    <% end %>

    <h1 class="title">Calendar</h1>

    <br>

    <div class="calendar-container">
      <%= Calendar.new(Date.new(2022, 01, 01), 12).show_calendar %>
    </div>
  </div>
  <div class="calendar-adminContainer">
    <h1>Admin stuff</h1>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bbonds</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <nav>
        <ul>
          <li>
            <%= link_to "Events", admin_events_path %>
          </li>
        </ul>
      </nav>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>